collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

baseurl: "/gunnarsolvi.github.io"
url: "https://gunnarsolvi88.github.io/gunnarsolvi.github.io/"
